# Definindo imagem de origem

FROM nginx:latest




# Executando comandos dentro da imagem

RUN apt-get update




# Definindo diretório de trabalho

WORKDIR /app




# Copiando arquivos para dentro da imagem

COPY ./html /usr/share/nginx/html